const ACTION = {
    ADD_NODE: "ADD_NODE",
    ADD_EDGES: "ADD_EDGES",
    DELETE_NODE: "DELETE_NODE",
    DELETE_EDGE: "DELETE_EDGE",
    SET_STARTNODE: "SET_STARTNODE",
    RESET_STARTNODE: "RESET_STARTNODE",
    SET_DESTINATIONNODE: "SET_DESTINATIONNODE",
    RESET_DESTINATIONNODE: "RESET_DESTINATIONNODE",
    SET_POSITION: "SET_POSITION",

//   SET_USER: "SET_USER",
//   RESET_USER: "RESET_USER",
//   CHECK_USER: "CHECK_USER",
//   SET_FEEDS: "SET_FEEDS",
};

export default ACTION;
